rm -rf ./Libraries/CMSIS/Device/ST/STM32F10x/Release_Notes.html
rm -rf ./Libraries/CMSIS/Device/ST/STM32F30x/Release_Notes.html
rm -rf ./Libraries/CMSIS/Device/ST/STM32F37x/Release_Notes.html
rm -rf ./Libraries/CMSIS/Device/ST/STM32L1xx/Release_Notes.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/annotated.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/classes.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/device_h_pg.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/functions.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/functions_vars.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/globals.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/globals_enum.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/globals_eval.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/globals_func.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/globals_vars.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/group__intrinsic___c_p_u__gr.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/group__intrinsic___s_i_m_d__gr.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/group__peripheral__gr.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/group__system__init__gr.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/group___core___register__gr.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/group___i_t_m___debug__gr.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/group___n_v_i_c__gr.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/group___sys_tick__gr.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/index.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/modules.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/pages.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_5f.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_61.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_62.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_63.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_64.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_65.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_66.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_68.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_69.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_6c.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_6d.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_6e.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_6f.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_70.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_71.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_72.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_73.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_74.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_75.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_76.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_77.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_78.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/all_7a.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/classes_61.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/classes_63.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/classes_64.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/classes_66.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/classes_69.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/classes_6d.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/classes_6e.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/classes_73.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/classes_74.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/classes_78.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/enums_69.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/enumvalues_62.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/enumvalues_64.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/enumvalues_68.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/enumvalues_6d.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/enumvalues_6e.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/enumvalues_70.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/enumvalues_73.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/enumvalues_75.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/enumvalues_77.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/files_6d.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/files_6f.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/files_72.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/files_74.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/files_75.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/functions_5f.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/functions_69.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/functions_6e.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/functions_73.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/nomatches.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_5f.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_61.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_62.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_63.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_64.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_65.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_66.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_68.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_69.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_6c.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_6d.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_6e.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_70.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_71.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_72.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_73.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_74.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_75.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_76.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_77.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/search/variables_7a.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/startup_s_pg.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/struct_core_debug___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/struct_d_w_t___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/struct_f_p_u___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/struct_i_t_m___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/struct_m_p_u___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/struct_n_v_i_c___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/struct_sys_tick___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/struct_s_cn_s_c_b___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/struct_s_c_b___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/struct_t_p_i___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/system_c_pg.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/unionx_p_s_r___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/union_a_p_s_r___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/union_c_o_n_t_r_o_l___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/union_i_p_s_r___type.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/_c_o_r_e__m_i_s_r_a__exceptions_pg.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/_reg_map_pg.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/_templates_pg.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/_using_pg.html
rm -rf ./Libraries/CMSIS/Documentation/Core/html/_using__a_r_m_pg.html
rm -rf ./Libraries/CMSIS/Documentation/General/html/index.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/annotated.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/classes.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/cmsis_os_h.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/cmsis__os_8h.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/cmsis__os_8txt.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/files.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/functions.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/functions_vars.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/globals.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/globals_defs.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/globals_enum.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/globals_eval.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/globals_func.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/globals_type.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___definitions.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___kernel_ctrl.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___mail.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___message.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___mutex_mgmt.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___pool_mgmt.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___semaphore_mgmt.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___signal_mgmt.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___status.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___thread_mgmt.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___timer_mgmt.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/group___c_m_s_i_s___r_t_o_s___wait.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/index.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/modules.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/pages.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/all_63.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/all_64.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/all_69.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/all_6d.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/all_6f.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/all_70.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/all_71.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/all_73.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/all_74.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/all_76.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/classes_6f.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/defines_6f.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/enums_6f.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/enumvalues_6f.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/files_63.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/functions_6f.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/nomatches.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/typedefs_6f.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/variables_64.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/variables_69.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/variables_6d.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/variables_70.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/variables_71.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/variables_73.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/variables_74.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/search/variables_76.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/structos_mail_q_def__t.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/structos_message_q_def__t.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/structos_mutex_def__t.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/structos_pool_def__t.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/structos_semaphore_def__t.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/structos_thread_def__t.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/structos_timer_def__t.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/_function_overview.html
rm -rf ./Libraries/CMSIS/Documentation/RTOS/html/_using_o_s.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__cluster_level__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__cpu_section__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__device_section_extensions__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__dim_element_group__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__elem__type__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__peripheral_section_extensions__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__register_properties_group__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__register_section_extensions__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__schema__1__1__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__schema__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__svd__xml__device__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__svd__xml__enum__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__svd__xml__fields__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__svd__xml__peripherals__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__svd__xml__registers__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__svd___format__1__1__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/group__svd___format__gr.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/index.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/modules.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/pages.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/svd_validate_file_pg.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/svd_web_pg.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/svd_web_public_pg.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/svd_web_restricted_pg.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/svd__example_pg.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/svd__outline_pg.html
rm -rf ./Libraries/CMSIS/Documentation/SVD/html/svd__usage_pg.html
rm -rf ./Libraries/CMSIS/index.html
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/Release_Notes.html
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/Release_Notes.html
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/Release_Notes.html
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/Release_Notes.html
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/Release_Notes.html
rm -rf ./Utilities/STM32_EVAL/Common/Release_Notes.html
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/Release_Notes.html
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/Release_Notes.html
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/Release_Notes.html
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/Release_Notes.html
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/Release_Notes.html
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/Release_Notes.html
