rm -rf ./Projects/Audio_Speaker/EWARM
rm -rf ./Projects/Composite_Example/EWARM
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/EWARM
rm -rf ./Projects/Device_Firmware_Upgrade/EWARM
rm -rf ./Projects/JoyStickMouse/EWARM
rm -rf ./Projects/Mass_Storage/EWARM
rm -rf ./Projects/VirtualComport_Loopback/EWARM
rm -rf ./Projects/Virtual_COM_Port/EWARM
rm -rf ./Projects/Audio_Speaker/RIDE
rm -rf ./Projects/Composite_Example/RIDE
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/RIDE
rm -rf ./Projects/Device_Firmware_Upgrade/RIDE
rm -rf ./Projects/JoyStickMouse/RIDE
rm -rf ./Projects/Mass_Storage/RIDE
rm -rf ./Projects/VirtualComport_Loopback/RIDE
rm -rf ./Projects/Virtual_COM_Port/RIDE
rm -rf ./Libraries/CMSIS/Device/ST/STM32F10x/Source/Templates/TASKING
rm -rf ./Libraries/CMSIS/Device/ST/STM32L1xx/Source/Templates/TASKING
rm -rf ./Projects/Audio_Speaker/TASKING
rm -rf ./Projects/Audio_Speaker/TASKING/STM3210B-EVAL/TASKING
rm -rf ./Projects/Audio_Speaker/TASKING/STM3210E-EVAL/TASKING
rm -rf ./Projects/Audio_Speaker/TASKING/STM3210E-EVAL_XL/TASKING
rm -rf ./Projects/Audio_Speaker/TASKING/STM32L152-EVAL/TASKING
rm -rf ./Projects/Composite_Example/TASKING
rm -rf ./Projects/Composite_Example/TASKING/STM3210B-EVAL/TASKING
rm -rf ./Projects/Composite_Example/TASKING/STM3210E-EVAL/TASKING
rm -rf ./Projects/Composite_Example/TASKING/STM3210E-EVAL_XL/TASKING
rm -rf ./Projects/Composite_Example/TASKING/STM32303C_EVAL/TASKING
rm -rf ./Projects/Composite_Example/TASKING/STM32373C_EVAL/TASKING
rm -rf ./Projects/Composite_Example/TASKING/STM32L152-EVAL/TASKING
rm -rf ./Projects/Composite_Example/TASKING/STM32L152D-EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/TASKING/STM3210B-EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/TASKING/STM3210E-EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/TASKING/STM3210E-EVAL_XL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/TASKING/STM32303C_EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/TASKING/STM32373C_EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/TASKING/STM32L152-EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/TASKING/STM32L152D-EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/TASKING/STM3210B-EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/TASKING/STM3210E-EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/TASKING/STM3210E-EVAL_XL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/TASKING/STM32303C_EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/TASKING/STM32373C_EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/TASKING/STM32L152-EVAL/TASKING
rm -rf ./Projects/Device_Firmware_Upgrade/TASKING/STM32L152D-EVAL/TASKING
rm -rf ./Projects/JoyStickMouse/TASKING
rm -rf ./Projects/JoyStickMouse/TASKING/STM3210B-EVAL/TASKING
rm -rf ./Projects/JoyStickMouse/TASKING/STM3210E-EVAL/TASKING
rm -rf ./Projects/JoyStickMouse/TASKING/STM3210E-EVAL_XL/TASKING
rm -rf ./Projects/JoyStickMouse/TASKING/STM32303C_EVAL/TASKING
rm -rf ./Projects/JoyStickMouse/TASKING/STM32373C_EVAL/TASKING
rm -rf ./Projects/JoyStickMouse/TASKING/STM32L152-EVAL/TASKING
rm -rf ./Projects/JoyStickMouse/TASKING/STM32L152D-EVAL/TASKING
rm -rf ./Projects/Mass_Storage/TASKING
rm -rf ./Projects/Mass_Storage/TASKING/STM3210B-EVAL/TASKING
rm -rf ./Projects/Mass_Storage/TASKING/STM3210E-EVAL/TASKING
rm -rf ./Projects/Mass_Storage/TASKING/STM3210E-EVAL_XL/TASKING
rm -rf ./Projects/Mass_Storage/TASKING/STM32303C_EVAL/TASKING
rm -rf ./Projects/Mass_Storage/TASKING/STM32373C_EVAL/TASKING
rm -rf ./Projects/Mass_Storage/TASKING/STM32L152-EVAL/TASKING
rm -rf ./Projects/Mass_Storage/TASKING/STM32L152D-EVAL/TASKING
rm -rf ./Projects/VirtualComport_Loopback/TASKING
rm -rf ./Projects/VirtualComport_Loopback/TASKING/STM3210B-EVAL/TASKING
rm -rf ./Projects/VirtualComport_Loopback/TASKING/STM3210E-EVAL/TASKING
rm -rf ./Projects/VirtualComport_Loopback/TASKING/STM3210E-EVAL_XL/TASKING
rm -rf ./Projects/VirtualComport_Loopback/TASKING/STM32303C_EVAL/TASKING
rm -rf ./Projects/VirtualComport_Loopback/TASKING/STM32373C_EVAL/TASKING
rm -rf ./Projects/VirtualComport_Loopback/TASKING/STM32L152-EVAL/TASKING
rm -rf ./Projects/VirtualComport_Loopback/TASKING/STM32L152D-EVAL/TASKING
rm -rf ./Projects/Virtual_COM_Port/TASKING
rm -rf ./Projects/Virtual_COM_Port/TASKING/STM3210B-EVAL/TASKING
rm -rf ./Projects/Virtual_COM_Port/TASKING/STM3210E-EVAL/TASKING
rm -rf ./Projects/Virtual_COM_Port/TASKING/STM3210E-EVAL_XL/TASKING
rm -rf ./Projects/Virtual_COM_Port/TASKING/STM32303C_EVAL/TASKING
rm -rf ./Projects/Virtual_COM_Port/TASKING/STM32373C_EVAL/TASKING
rm -rf ./Projects/Virtual_COM_Port/TASKING/STM32L152-EVAL/TASKING
rm -rf ./Projects/Virtual_COM_Port/TASKING/STM32L152D-EVAL/TASKING
rm -rf ./Libraries/CMSIS/Device/ST/STM32F10x/Source/Templates/TrueSTUDIO
rm -rf ./Libraries/CMSIS/Device/ST/STM32F30x/Source/Templates/TrueSTUDIO
rm -rf ./Libraries/CMSIS/Device/ST/STM32F37x/Source/Templates/TrueSTUDIO
rm -rf ./Libraries/CMSIS/Device/ST/STM32L1xx/Source/Templates/TrueSTUDIO
rm -rf ./Projects/Audio_Speaker/TrueSTUDIO
rm -rf ./Projects/Composite_Example/TrueSTUDIO
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/TrueSTUDIO
rm -rf ./Projects/Device_Firmware_Upgrade/TrueSTUDIO
rm -rf ./Projects/JoyStickMouse/TrueSTUDIO
rm -rf ./Projects/Mass_Storage/TrueSTUDIO
rm -rf ./Projects/VirtualComport_Loopback/TrueSTUDIO
rm -rf ./Projects/Virtual_COM_Port/TrueSTUDIO
