indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32F10x/Source/Templates/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32F30x/Source/Templates/system_stm32f30x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32F37x/Source/Templates/system_stm32f37x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32L1xx/Source/Templates/system_stm32l1xx.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/misc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_adc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_can.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_comp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_crc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dac.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dbgmcu.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dma.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_exti.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_flash.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_gpio.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_i2c.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_iwdg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_misc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_opamp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rcc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rtc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_spi.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_syscfg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_tim.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_usart.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_wwdg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_adc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_can.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_cec.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_comp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_crc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_dac.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_dbgmcu.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_dma.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_exti.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_flash.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_gpio.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_i2c.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_iwdg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_misc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_rcc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_rtc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_sdadc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_spi.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_syscfg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_tim.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_usart.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_wwdg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/misc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_adc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_aes.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_aes_util.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_comp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_crc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dac.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dbgmcu.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dma.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_exti.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_flash.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_flash_ramfunc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_fsmc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_gpio.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_i2c.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_iwdg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_lcd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_opamp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_rcc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_rtc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_sdio.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_spi.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_syscfg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_tim.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_usart.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_wwdg.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/src/usb_core.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/src/usb_init.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/src/usb_int.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/src/usb_mem.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/src/usb_regs.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/src/usb_sil.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/hw_config.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/i2s_codec.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/main.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/stm32_it.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/system_stm32l1xx.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/usb_desc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/usb_endp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/usb_istr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/usb_prop.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/src/usb_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/fsmc_nand.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/hw_config.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/main.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/mass_mal.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/memory.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/nand_if.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/scsi_data.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/stm32_it.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/system_stm32f30x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/system_stm32f37x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/system_stm32l1xx.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/usb_bot.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/usb_desc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/usb_endp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/usb_istr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/usb_prop.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/usb_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/src/usb_scsi.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/hw_config.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/main.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/stm32_it.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/system_stm32f30x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/system_stm32f37x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/system_stm32l1xx.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/usb_desc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/usb_endp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/usb_istr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/usb_prop.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/src/usb_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/src/main.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/src/stm32_it.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/src/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/src/system_stm32f30x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/src/system_stm32f37x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/src/system_stm32l1xx.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/dfu_mal.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/flash_if.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/fsmc_nor.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/hw_config.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/main.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/nor_if.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/spi_if.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/stm32_it.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/system_stm32f30x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/system_stm32f37x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/system_stm32l1xx.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/usb_desc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/usb_istr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/usb_prop.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/src/usb_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/hw_config.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/main.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/stm32_it.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/system_stm32f30x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/system_stm32f37x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/system_stm32l1xx.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/usb_desc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/usb_endp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/usb_istr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/usb_prop.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/src/usb_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/fsmc_nand.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/hw_config.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/main.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/mass_mal.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/memory.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/nand_if.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/scsi_data.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/stm32_it.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/system_stm32f30x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/system_stm32f37x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/system_stm32l1xx.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/usb_bot.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/usb_desc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/usb_endp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/usb_istr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/usb_prop.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/usb_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/src/usb_scsi.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/hw_config.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/main.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/stm32_it.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/system_stm32f30x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/system_stm32f37x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/system_stm32l1xx.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/usb_desc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/usb_endp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/usb_istr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/usb_prop.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/src/usb_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/hw_config.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/main.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/stm32_it.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/system_stm32f10x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/system_stm32f30x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/system_stm32f37x.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/system_stm32l1xx.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/usb_desc.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/usb_endp.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/usb_istr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/usb_prop.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/src/usb_pwr.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/Common/fonts.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/Common/lcd_log.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/debug.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/misc_lib.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_i2c_tsensor.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_lcd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_spi_flash.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_spi_sd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/sys_timer.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_nand.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_nor.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_sram.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_i2c_tsensor.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_lcd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_sdio_sd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_spi_flash.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_audio_codec.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_ee.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_ee_cpal.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_tsensor.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_lcd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_spi_ee.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_spi_sd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_audio_codec.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_cec.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_ee.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_ee_cpal.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_tsensor.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_tsensor_cpal.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_lcd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_spi_sd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_audio_codec.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_fsmc_nor.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_fsmc_sram.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_glass_lcd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_i2c_ee.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_i2c_tsensor.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_lcd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_sdio_sd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_spi_ee.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_glass_lcd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_i2c_ee.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_i2c_tsensor.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_lcd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_spi_sd.c
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32F10x/Include/stm32f10x.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32F10x/Include/system_stm32f10x.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32F30x/Include/stm32f30x.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32F30x/Include/system_stm32f30x.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32F37x/Include/stm32f37x.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32F37x/Include/system_stm32f37x.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32L1xx/Include/stm32l1xx.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Device/ST/STM32L1xx/Include/system_stm32l1xx.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/arm_common_tables.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/arm_math.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/core_cm0.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/core_cm0plus.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/core_cm3.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/core_cm4.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/core_cm4_simd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/core_cmFunc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/core_cmInstr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/core_sc000.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/Include/core_sc300.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/CMSIS/RTOS/cmsis_os.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/misc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_adc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_bkp.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_can.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_cec.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_crc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_dac.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_dbgmcu.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_dma.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_exti.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_flash.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_fsmc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_gpio.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_i2c.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_iwdg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_rcc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_rtc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_sdio.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_spi.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_tim.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_usart.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_wwdg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_adc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_can.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_comp.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_crc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_dac.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_dbgmcu.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_dma.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_exti.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_flash.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_gpio.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_i2c.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_iwdg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_misc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_opamp.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_rcc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_rtc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_spi.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_syscfg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_tim.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_usart.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_wwdg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_adc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_can.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_cec.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_comp.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_crc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_dac.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_dbgmcu.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_dma.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_exti.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_flash.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_gpio.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_i2c.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_iwdg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_misc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_rcc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_rtc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_sdadc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_spi.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_syscfg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_tim.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_usart.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_wwdg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/misc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_adc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_aes.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_comp.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_crc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_dac.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_dbgmcu.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_dma.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_exti.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_flash.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_fsmc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_gpio.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_i2c.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_iwdg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_lcd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_opamp.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_rcc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_rtc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_sdio.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_spi.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_syscfg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_tim.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_usart.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_wwdg.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_core.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_def.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_init.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_int.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_lib.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_mem.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_regs.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_sil.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_type.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/hw_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/i2s_codec.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/platform_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/stm32f10x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/stm32l1xx_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/stm32_it.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/usb_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/usb_desc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/usb_istr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/usb_prop.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Audio_Speaker/inc/usb_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/fsmc_nand.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/hw_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/mass_mal.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/memory.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/nand_if.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/platform_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/stm32f10x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/stm32f30x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/stm32f37x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/stm32l1xx_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/stm32_it.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/usb_bot.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/usb_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/usb_desc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/usb_istr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/usb_prop.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/usb_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Composite_Example/inc/usb_scsi.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/hw_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/platform_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/stm32f10x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/stm32f30x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/stm32f37x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/stm32l1xx_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/stm32_it.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/usb_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/usb_desc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/usb_istr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/usb_prop.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Custom_HID/inc/usb_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/inc/main.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/inc/platform_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/inc/stm32f10x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/inc/stm32f30x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/inc/stm32f37x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/inc/stm32l1xx_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/binary_template/inc/stm32_it.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/dfu_mal.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/flash_if.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/fsmc_nor.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/hw_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/nor_if.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/platform_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/spi_if.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/stm32f10x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/stm32f30x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/stm32f37x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/stm32l1xx_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/stm32_it.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/usb_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/usb_desc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/usb_istr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/usb_prop.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Device_Firmware_Upgrade/inc/usb_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/hw_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/platform_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/stm32f10x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/stm32f30x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/stm32f37x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/stm32l1xx_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/stm32_it.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/usb_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/usb_desc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/usb_istr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/usb_prop.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/JoyStickMouse/inc/usb_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/fsmc_nand.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/hw_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/mass_mal.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/memory.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/nand_if.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/platform_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/stm32f10x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/stm32f30x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/stm32f37x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/stm32l1xx_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/stm32_it.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/usb_bot.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/usb_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/usb_desc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/usb_istr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/usb_prop.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/usb_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Mass_Storage/inc/usb_scsi.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/hw_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/platform_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/stm32f10x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/stm32f30x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/stm32f37x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/stm32l1xx_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/stm32_it.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/usb_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/usb_desc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/usb_istr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/usb_prop.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/VirtualComport_Loopback/inc/usb_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/hw_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/platform_config.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/stm32f10x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/stm32f30x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/stm32f37x_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/stm32l1xx_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/stm32_it.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/usb_conf.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/usb_desc.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/usb_istr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/usb_prop.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Projects/Virtual_COM_Port/inc/usb_pwr.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/Common/fonts.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/Common/lcd_log.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/Common/lcd_log_conf_template.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/Common/stm32_eval_legacy.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/debug.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/misc_lib.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_i2c_tsensor.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_lcd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_spi_flash.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_spi_sd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210B_EVAL/sys_timer.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_nand.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_nor.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_sram.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_i2c_tsensor.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_lcd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_sdio_sd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_spi_flash.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_audio_codec.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_ee.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_ee_cpal.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_tsensor.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_lcd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_spi_ee.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_spi_sd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_audio_codec.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_cec.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_ee.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_ee_cpal.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_tsensor.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_tsensor_cpal.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_lcd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_spi_sd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_audio_codec.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_fsmc_nor.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_fsmc_sram.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_glass_lcd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_i2c_ee.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_i2c_tsensor.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_lcd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_sdio_sd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_spi_ee.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_glass_lcd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_i2c_ee.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_i2c_tsensor.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_lcd.h
indent -npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_spi_sd.h
