rm -rf ./Libraries/CMSIS/Device/ST/STM32F10x/Include/stm32f10x.h~
rm -rf ./Libraries/CMSIS/Device/ST/STM32F10x/Include/system_stm32f10x.h~
rm -rf ./Libraries/CMSIS/Device/ST/STM32F10x/Source/Templates/system_stm32f10x.c~
rm -rf ./Libraries/CMSIS/Device/ST/STM32F30x/Include/stm32f30x.h~
rm -rf ./Libraries/CMSIS/Device/ST/STM32F30x/Include/system_stm32f30x.h~
rm -rf ./Libraries/CMSIS/Device/ST/STM32F30x/Source/Templates/system_stm32f30x.c~
rm -rf ./Libraries/CMSIS/Device/ST/STM32F37x/Include/stm32f37x.h~
rm -rf ./Libraries/CMSIS/Device/ST/STM32F37x/Include/system_stm32f37x.h~
rm -rf ./Libraries/CMSIS/Device/ST/STM32F37x/Source/Templates/system_stm32f37x.c~
rm -rf ./Libraries/CMSIS/Device/ST/STM32L1xx/Include/stm32l1xx.h~
rm -rf ./Libraries/CMSIS/Device/ST/STM32L1xx/Include/system_stm32l1xx.h~
rm -rf ./Libraries/CMSIS/Device/ST/STM32L1xx/Source/Templates/system_stm32l1xx.c~
rm -rf ./Libraries/CMSIS/Include/arm_common_tables.h~
rm -rf ./Libraries/CMSIS/Include/arm_math.h~
rm -rf ./Libraries/CMSIS/Include/core_cm0.h~
rm -rf ./Libraries/CMSIS/Include/core_cm0plus.h~
rm -rf ./Libraries/CMSIS/Include/core_cm3.h~
rm -rf ./Libraries/CMSIS/Include/core_cm4.h~
rm -rf ./Libraries/CMSIS/Include/core_cm4_simd.h~
rm -rf ./Libraries/CMSIS/Include/core_cmFunc.h~
rm -rf ./Libraries/CMSIS/Include/core_cmInstr.h~
rm -rf ./Libraries/CMSIS/Include/core_sc000.h~
rm -rf ./Libraries/CMSIS/Include/core_sc300.h~
rm -rf ./Libraries/CMSIS/RTOS/cmsis_os.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/misc.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_adc.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_bkp.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_can.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_cec.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_crc.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_dac.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_dbgmcu.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_dma.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_exti.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_flash.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_fsmc.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_gpio.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_i2c.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_iwdg.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_pwr.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_rcc.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_rtc.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_sdio.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_spi.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_tim.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_usart.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/inc/stm32f10x_wwdg.h~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/misc.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c~
rm -rf ./Libraries/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_adc.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_can.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_comp.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_crc.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_dac.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_dbgmcu.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_dma.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_exti.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_flash.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_gpio.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_i2c.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_iwdg.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_misc.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_opamp.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_pwr.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_rcc.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_rtc.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_spi.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_syscfg.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_tim.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_usart.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/inc/stm32f30x_wwdg.h~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_adc.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_can.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_comp.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_crc.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dac.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dbgmcu.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_dma.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_exti.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_flash.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_gpio.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_i2c.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_iwdg.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_misc.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_opamp.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_pwr.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rcc.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_rtc.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_spi.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_syscfg.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_tim.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_usart.c~
rm -rf ./Libraries/STM32F30x_StdPeriph_Driver/src/stm32f30x_wwdg.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_adc.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_can.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_cec.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_comp.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_crc.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_dac.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_dbgmcu.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_dma.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_exti.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_flash.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_gpio.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_i2c.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_iwdg.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_misc.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_pwr.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_rcc.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_rtc.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_sdadc.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_spi.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_syscfg.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_tim.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_usart.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/inc/stm32f37x_wwdg.h~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_adc.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_can.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_cec.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_comp.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_crc.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_dac.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_dbgmcu.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_dma.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_exti.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_flash.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_gpio.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_i2c.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_iwdg.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_misc.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_pwr.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_rcc.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_rtc.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_sdadc.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_spi.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_syscfg.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_tim.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_usart.c~
rm -rf ./Libraries/STM32F37x_StdPeriph_Driver/src/stm32f37x_wwdg.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/misc.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_adc.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_aes.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_comp.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_crc.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_dac.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_dbgmcu.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_dma.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_exti.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_flash.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_fsmc.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_gpio.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_i2c.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_iwdg.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_lcd.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_opamp.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_pwr.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_rcc.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_rtc.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_sdio.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_spi.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_syscfg.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_tim.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_usart.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/inc/stm32l1xx_wwdg.h~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/misc.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_adc.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_aes.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_aes_util.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_comp.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_crc.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dac.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dbgmcu.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_dma.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_exti.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_flash.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_flash_ramfunc.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_fsmc.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_gpio.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_i2c.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_iwdg.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_lcd.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_opamp.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_pwr.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_rcc.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_rtc.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_sdio.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_spi.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_syscfg.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_tim.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_usart.c~
rm -rf ./Libraries/STM32L1xx_StdPeriph_Driver/src/stm32l1xx_wwdg.c~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_core.h~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_def.h~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_init.h~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_int.h~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_lib.h~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_mem.h~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_regs.h~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_sil.h~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/inc/usb_type.h~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/src/usb_core.c~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/src/usb_init.c~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/src/usb_int.c~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/src/usb_mem.c~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/src/usb_regs.c~
rm -rf ./Libraries/STM32_USB-FS-Device_Driver/src/usb_sil.c~
rm -rf ./Projects/Audio_Speaker/inc/hw_config.h~
rm -rf ./Projects/Audio_Speaker/inc/i2s_codec.h~
rm -rf ./Projects/Audio_Speaker/inc/platform_config.h~
rm -rf ./Projects/Audio_Speaker/inc/stm32f10x_conf.h~
rm -rf ./Projects/Audio_Speaker/inc/stm32l1xx_conf.h~
rm -rf ./Projects/Audio_Speaker/inc/stm32_it.h~
rm -rf ./Projects/Audio_Speaker/inc/usb_conf.h~
rm -rf ./Projects/Audio_Speaker/inc/usb_desc.h~
rm -rf ./Projects/Audio_Speaker/inc/usb_istr.h~
rm -rf ./Projects/Audio_Speaker/inc/usb_prop.h~
rm -rf ./Projects/Audio_Speaker/inc/usb_pwr.h~
rm -rf ./Projects/Audio_Speaker/src/hw_config.c~
rm -rf ./Projects/Audio_Speaker/src/i2s_codec.c~
rm -rf ./Projects/Audio_Speaker/src/main.c~
rm -rf ./Projects/Audio_Speaker/src/stm32_it.c~
rm -rf ./Projects/Audio_Speaker/src/system_stm32f10x.c~
rm -rf ./Projects/Audio_Speaker/src/system_stm32l1xx.c~
rm -rf ./Projects/Audio_Speaker/src/usb_desc.c~
rm -rf ./Projects/Audio_Speaker/src/usb_endp.c~
rm -rf ./Projects/Audio_Speaker/src/usb_istr.c~
rm -rf ./Projects/Audio_Speaker/src/usb_prop.c~
rm -rf ./Projects/Audio_Speaker/src/usb_pwr.c~
rm -rf ./Projects/Composite_Example/inc/fsmc_nand.h~
rm -rf ./Projects/Composite_Example/inc/hw_config.h~
rm -rf ./Projects/Composite_Example/inc/mass_mal.h~
rm -rf ./Projects/Composite_Example/inc/memory.h~
rm -rf ./Projects/Composite_Example/inc/nand_if.h~
rm -rf ./Projects/Composite_Example/inc/platform_config.h~
rm -rf ./Projects/Composite_Example/inc/stm32f10x_conf.h~
rm -rf ./Projects/Composite_Example/inc/stm32f30x_conf.h~
rm -rf ./Projects/Composite_Example/inc/stm32f37x_conf.h~
rm -rf ./Projects/Composite_Example/inc/stm32l1xx_conf.h~
rm -rf ./Projects/Composite_Example/inc/stm32_it.h~
rm -rf ./Projects/Composite_Example/inc/usb_bot.h~
rm -rf ./Projects/Composite_Example/inc/usb_conf.h~
rm -rf ./Projects/Composite_Example/inc/usb_desc.h~
rm -rf ./Projects/Composite_Example/inc/usb_istr.h~
rm -rf ./Projects/Composite_Example/inc/usb_prop.h~
rm -rf ./Projects/Composite_Example/inc/usb_pwr.h~
rm -rf ./Projects/Composite_Example/inc/usb_scsi.h~
rm -rf ./Projects/Composite_Example/src/fsmc_nand.c~
rm -rf ./Projects/Composite_Example/src/hw_config.c~
rm -rf ./Projects/Composite_Example/src/main.c~
rm -rf ./Projects/Composite_Example/src/mass_mal.c~
rm -rf ./Projects/Composite_Example/src/memory.c~
rm -rf ./Projects/Composite_Example/src/nand_if.c~
rm -rf ./Projects/Composite_Example/src/scsi_data.c~
rm -rf ./Projects/Composite_Example/src/stm32_it.c~
rm -rf ./Projects/Composite_Example/src/system_stm32f10x.c~
rm -rf ./Projects/Composite_Example/src/system_stm32f30x.c~
rm -rf ./Projects/Composite_Example/src/system_stm32f37x.c~
rm -rf ./Projects/Composite_Example/src/system_stm32l1xx.c~
rm -rf ./Projects/Composite_Example/src/usb_bot.c~
rm -rf ./Projects/Composite_Example/src/usb_desc.c~
rm -rf ./Projects/Composite_Example/src/usb_endp.c~
rm -rf ./Projects/Composite_Example/src/usb_istr.c~
rm -rf ./Projects/Composite_Example/src/usb_prop.c~
rm -rf ./Projects/Composite_Example/src/usb_pwr.c~
rm -rf ./Projects/Composite_Example/src/usb_scsi.c~
rm -rf ./Projects/Custom_HID/inc/hw_config.h~
rm -rf ./Projects/Custom_HID/inc/platform_config.h~
rm -rf ./Projects/Custom_HID/inc/stm32f10x_conf.h~
rm -rf ./Projects/Custom_HID/inc/stm32f30x_conf.h~
rm -rf ./Projects/Custom_HID/inc/stm32f37x_conf.h~
rm -rf ./Projects/Custom_HID/inc/stm32l1xx_conf.h~
rm -rf ./Projects/Custom_HID/inc/stm32_it.h~
rm -rf ./Projects/Custom_HID/inc/usb_conf.h~
rm -rf ./Projects/Custom_HID/inc/usb_desc.h~
rm -rf ./Projects/Custom_HID/inc/usb_istr.h~
rm -rf ./Projects/Custom_HID/inc/usb_prop.h~
rm -rf ./Projects/Custom_HID/inc/usb_pwr.h~
rm -rf ./Projects/Custom_HID/src/hw_config.c~
rm -rf ./Projects/Custom_HID/src/main.c~
rm -rf ./Projects/Custom_HID/src/stm32_it.c~
rm -rf ./Projects/Custom_HID/src/system_stm32f10x.c~
rm -rf ./Projects/Custom_HID/src/system_stm32f30x.c~
rm -rf ./Projects/Custom_HID/src/system_stm32f37x.c~
rm -rf ./Projects/Custom_HID/src/system_stm32l1xx.c~
rm -rf ./Projects/Custom_HID/src/usb_desc.c~
rm -rf ./Projects/Custom_HID/src/usb_endp.c~
rm -rf ./Projects/Custom_HID/src/usb_istr.c~
rm -rf ./Projects/Custom_HID/src/usb_prop.c~
rm -rf ./Projects/Custom_HID/src/usb_pwr.c~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/inc/main.h~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/inc/platform_config.h~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/inc/stm32f10x_conf.h~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/inc/stm32f30x_conf.h~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/inc/stm32f37x_conf.h~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/inc/stm32l1xx_conf.h~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/inc/stm32_it.h~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/src/main.c~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/src/stm32_it.c~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/src/system_stm32f10x.c~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/src/system_stm32f30x.c~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/src/system_stm32f37x.c~
rm -rf ./Projects/Device_Firmware_Upgrade/binary_template/src/system_stm32l1xx.c~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/dfu_mal.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/flash_if.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/fsmc_nor.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/hw_config.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/nor_if.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/platform_config.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/spi_if.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/stm32f10x_conf.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/stm32f30x_conf.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/stm32f37x_conf.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/stm32l1xx_conf.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/stm32_it.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/usb_conf.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/usb_desc.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/usb_istr.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/usb_prop.h~
rm -rf ./Projects/Device_Firmware_Upgrade/inc/usb_pwr.h~
rm -rf ./Projects/Device_Firmware_Upgrade/src/dfu_mal.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/flash_if.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/fsmc_nor.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/hw_config.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/main.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/nor_if.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/spi_if.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/stm32_it.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/system_stm32f10x.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/system_stm32f30x.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/system_stm32f37x.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/system_stm32l1xx.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/usb_desc.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/usb_istr.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/usb_prop.c~
rm -rf ./Projects/Device_Firmware_Upgrade/src/usb_pwr.c~
rm -rf ./Projects/JoyStickMouse/inc/hw_config.h~
rm -rf ./Projects/JoyStickMouse/inc/platform_config.h~
rm -rf ./Projects/JoyStickMouse/inc/stm32f10x_conf.h~
rm -rf ./Projects/JoyStickMouse/inc/stm32f30x_conf.h~
rm -rf ./Projects/JoyStickMouse/inc/stm32f37x_conf.h~
rm -rf ./Projects/JoyStickMouse/inc/stm32l1xx_conf.h~
rm -rf ./Projects/JoyStickMouse/inc/stm32_it.h~
rm -rf ./Projects/JoyStickMouse/inc/usb_conf.h~
rm -rf ./Projects/JoyStickMouse/inc/usb_desc.h~
rm -rf ./Projects/JoyStickMouse/inc/usb_istr.h~
rm -rf ./Projects/JoyStickMouse/inc/usb_prop.h~
rm -rf ./Projects/JoyStickMouse/inc/usb_pwr.h~
rm -rf ./Projects/JoyStickMouse/src/hw_config.c~
rm -rf ./Projects/JoyStickMouse/src/main.c~
rm -rf ./Projects/JoyStickMouse/src/stm32_it.c~
rm -rf ./Projects/JoyStickMouse/src/system_stm32f10x.c~
rm -rf ./Projects/JoyStickMouse/src/system_stm32f30x.c~
rm -rf ./Projects/JoyStickMouse/src/system_stm32f37x.c~
rm -rf ./Projects/JoyStickMouse/src/system_stm32l1xx.c~
rm -rf ./Projects/JoyStickMouse/src/usb_desc.c~
rm -rf ./Projects/JoyStickMouse/src/usb_endp.c~
rm -rf ./Projects/JoyStickMouse/src/usb_istr.c~
rm -rf ./Projects/JoyStickMouse/src/usb_prop.c~
rm -rf ./Projects/JoyStickMouse/src/usb_pwr.c~
rm -rf ./Projects/Mass_Storage/inc/fsmc_nand.h~
rm -rf ./Projects/Mass_Storage/inc/hw_config.h~
rm -rf ./Projects/Mass_Storage/inc/mass_mal.h~
rm -rf ./Projects/Mass_Storage/inc/memory.h~
rm -rf ./Projects/Mass_Storage/inc/nand_if.h~
rm -rf ./Projects/Mass_Storage/inc/platform_config.h~
rm -rf ./Projects/Mass_Storage/inc/stm32f10x_conf.h~
rm -rf ./Projects/Mass_Storage/inc/stm32f30x_conf.h~
rm -rf ./Projects/Mass_Storage/inc/stm32f37x_conf.h~
rm -rf ./Projects/Mass_Storage/inc/stm32l1xx_conf.h~
rm -rf ./Projects/Mass_Storage/inc/stm32_it.h~
rm -rf ./Projects/Mass_Storage/inc/usb_bot.h~
rm -rf ./Projects/Mass_Storage/inc/usb_conf.h~
rm -rf ./Projects/Mass_Storage/inc/usb_desc.h~
rm -rf ./Projects/Mass_Storage/inc/usb_istr.h~
rm -rf ./Projects/Mass_Storage/inc/usb_prop.h~
rm -rf ./Projects/Mass_Storage/inc/usb_pwr.h~
rm -rf ./Projects/Mass_Storage/inc/usb_scsi.h~
rm -rf ./Projects/Mass_Storage/src/fsmc_nand.c~
rm -rf ./Projects/Mass_Storage/src/hw_config.c~
rm -rf ./Projects/Mass_Storage/src/main.c~
rm -rf ./Projects/Mass_Storage/src/mass_mal.c~
rm -rf ./Projects/Mass_Storage/src/memory.c~
rm -rf ./Projects/Mass_Storage/src/nand_if.c~
rm -rf ./Projects/Mass_Storage/src/scsi_data.c~
rm -rf ./Projects/Mass_Storage/src/stm32_it.c~
rm -rf ./Projects/Mass_Storage/src/system_stm32f10x.c~
rm -rf ./Projects/Mass_Storage/src/system_stm32f30x.c~
rm -rf ./Projects/Mass_Storage/src/system_stm32f37x.c~
rm -rf ./Projects/Mass_Storage/src/system_stm32l1xx.c~
rm -rf ./Projects/Mass_Storage/src/usb_bot.c~
rm -rf ./Projects/Mass_Storage/src/usb_desc.c~
rm -rf ./Projects/Mass_Storage/src/usb_endp.c~
rm -rf ./Projects/Mass_Storage/src/usb_istr.c~
rm -rf ./Projects/Mass_Storage/src/usb_prop.c~
rm -rf ./Projects/Mass_Storage/src/usb_pwr.c~
rm -rf ./Projects/Mass_Storage/src/usb_scsi.c~
rm -rf ./Projects/VirtualComport_Loopback/inc/hw_config.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/platform_config.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/stm32f10x_conf.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/stm32f30x_conf.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/stm32f37x_conf.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/stm32l1xx_conf.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/stm32_it.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/usb_conf.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/usb_desc.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/usb_istr.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/usb_prop.h~
rm -rf ./Projects/VirtualComport_Loopback/inc/usb_pwr.h~
rm -rf ./Projects/VirtualComport_Loopback/src/hw_config.c~
rm -rf ./Projects/VirtualComport_Loopback/src/main.c~
rm -rf ./Projects/VirtualComport_Loopback/src/stm32_it.c~
rm -rf ./Projects/VirtualComport_Loopback/src/system_stm32f10x.c~
rm -rf ./Projects/VirtualComport_Loopback/src/system_stm32f30x.c~
rm -rf ./Projects/VirtualComport_Loopback/src/system_stm32f37x.c~
rm -rf ./Projects/VirtualComport_Loopback/src/system_stm32l1xx.c~
rm -rf ./Projects/VirtualComport_Loopback/src/usb_desc.c~
rm -rf ./Projects/VirtualComport_Loopback/src/usb_endp.c~
rm -rf ./Projects/VirtualComport_Loopback/src/usb_istr.c~
rm -rf ./Projects/VirtualComport_Loopback/src/usb_prop.c~
rm -rf ./Projects/VirtualComport_Loopback/src/usb_pwr.c~
rm -rf ./Projects/Virtual_COM_Port/inc/hw_config.h~
rm -rf ./Projects/Virtual_COM_Port/inc/platform_config.h~
rm -rf ./Projects/Virtual_COM_Port/inc/stm32f10x_conf.h~
rm -rf ./Projects/Virtual_COM_Port/inc/stm32f30x_conf.h~
rm -rf ./Projects/Virtual_COM_Port/inc/stm32f37x_conf.h~
rm -rf ./Projects/Virtual_COM_Port/inc/stm32l1xx_conf.h~
rm -rf ./Projects/Virtual_COM_Port/inc/stm32_it.h~
rm -rf ./Projects/Virtual_COM_Port/inc/usb_conf.h~
rm -rf ./Projects/Virtual_COM_Port/inc/usb_desc.h~
rm -rf ./Projects/Virtual_COM_Port/inc/usb_istr.h~
rm -rf ./Projects/Virtual_COM_Port/inc/usb_prop.h~
rm -rf ./Projects/Virtual_COM_Port/inc/usb_pwr.h~
rm -rf ./Projects/Virtual_COM_Port/src/hw_config.c~
rm -rf ./Projects/Virtual_COM_Port/src/main.c~
rm -rf ./Projects/Virtual_COM_Port/src/stm32_it.c~
rm -rf ./Projects/Virtual_COM_Port/src/system_stm32f10x.c~
rm -rf ./Projects/Virtual_COM_Port/src/system_stm32f30x.c~
rm -rf ./Projects/Virtual_COM_Port/src/system_stm32f37x.c~
rm -rf ./Projects/Virtual_COM_Port/src/system_stm32l1xx.c~
rm -rf ./Projects/Virtual_COM_Port/src/usb_desc.c~
rm -rf ./Projects/Virtual_COM_Port/src/usb_endp.c~
rm -rf ./Projects/Virtual_COM_Port/src/usb_istr.c~
rm -rf ./Projects/Virtual_COM_Port/src/usb_prop.c~
rm -rf ./Projects/Virtual_COM_Port/src/usb_pwr.c~
rm -rf ./Utilities/STM32_EVAL/Common/fonts.c~
rm -rf ./Utilities/STM32_EVAL/Common/fonts.h~
rm -rf ./Utilities/STM32_EVAL/Common/lcd_log.c~
rm -rf ./Utilities/STM32_EVAL/Common/lcd_log.h~
rm -rf ./Utilities/STM32_EVAL/Common/lcd_log_conf_template.h~
rm -rf ./Utilities/STM32_EVAL/Common/stm32_eval_legacy.h~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/debug.c~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/debug.h~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/misc_lib.c~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/misc_lib.h~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval.c~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval.h~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_i2c_tsensor.c~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_i2c_tsensor.h~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_lcd.c~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_lcd.h~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_spi_flash.c~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_spi_flash.h~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_spi_sd.c~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/stm3210b_eval_spi_sd.h~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/sys_timer.c~
rm -rf ./Utilities/STM32_EVAL/STM3210B_EVAL/sys_timer.h~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval.c~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval.h~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_nand.c~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_nand.h~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_nor.c~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_nor.h~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_sram.c~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_fsmc_sram.h~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_i2c_tsensor.c~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_i2c_tsensor.h~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_lcd.c~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_lcd.h~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_sdio_sd.c~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_sdio_sd.h~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_spi_flash.c~
rm -rf ./Utilities/STM32_EVAL/STM3210E_EVAL/stm3210e_eval_spi_flash.h~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval.c~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval.h~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_audio_codec.c~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_audio_codec.h~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_ee.c~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_ee.h~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_ee_cpal.c~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_ee_cpal.h~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_tsensor.c~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_i2c_tsensor.h~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_lcd.c~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_lcd.h~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_spi_ee.c~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_spi_ee.h~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_spi_sd.c~
rm -rf ./Utilities/STM32_EVAL/STM32303C_EVAL/stm32303c_eval_spi_sd.h~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval.c~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval.h~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_audio_codec.c~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_audio_codec.h~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_cec.c~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_cec.h~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_ee.c~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_ee.h~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_ee_cpal.c~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_ee_cpal.h~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_tsensor.c~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_tsensor.h~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_tsensor_cpal.c~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_i2c_tsensor_cpal.h~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_lcd.c~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_lcd.h~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_spi_sd.c~
rm -rf ./Utilities/STM32_EVAL/STM32373C_EVAL/stm32373c_eval_spi_sd.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_audio_codec.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_audio_codec.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_fsmc_nor.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_fsmc_nor.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_fsmc_sram.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_fsmc_sram.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_glass_lcd.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_glass_lcd.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_i2c_ee.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_i2c_ee.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_i2c_tsensor.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_i2c_tsensor.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_lcd.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_lcd.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_sdio_sd.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_sdio_sd.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_spi_ee.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152D_EVAL/stm32l152d_eval_spi_ee.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_glass_lcd.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_glass_lcd.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_i2c_ee.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_i2c_ee.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_i2c_tsensor.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_i2c_tsensor.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_lcd.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_lcd.h~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_spi_sd.c~
rm -rf ./Utilities/STM32_EVAL/STM32L152_EVAL/stm32l152_eval_spi_sd.h~
